fail_fast: true
repos:

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    hooks:
      - id: clang-format
        types_or: [c++, c, objective-c++]
        files: \.(cc|mm|h)$

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: bash -c 'uv run ruff format'
        language: system
        files: \.py$
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        entry: bash -c 'uv run ruff check --fix'
        language: system
        files: \.py$
        pass_filenames: false
      - id: pyright
        name: pyright
        entry: bash -c 'uv run pyright'
        language: system
        pass_filenames: false
        always_run: true
      - id: build
        name: build
        entry: bash -c 'uv pip install -e . -q'
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest
        name: pytest
        entry: bash -c 'CI=true uv run pytest -q'
        language: system
        pass_filenames: false
        always_run: true
